version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    # You can also specify other tool versions:
    # nodejs: "19"
    # rust: "1.64"
    # golang: "1.19"


sphinx:
  configuration: docs/source/conf.py

python:
  version: 3.8
  install:
    - requirements: docs/requirements.txt

formats: all

