version: 2

build:
  image: latest
  environment:
    - EXAMPLE_ENV_VAR: value

sphinx:
  configuration: docs/source/conf.py

python:
  version: 3.8
  install:
    - requirements: docs/requirements.txt

formats: all

